name: Deploy to Azure VM

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      - name: Build application
        run: npm run build
        working-directory: frontend/
        
  deploy:
    needs: build
    runs-on: ubuntu-22.04

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt
      
          
      - name: Copy build artifacts to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: shubhrad1
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          source: backend/build/
          target: "/home/shubhrad-01/backend"
        

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: shubhrad1
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd shubhrad-01
            git pull
            source env/bin/activate
            cd backend
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --no-input
            
            

