name: Production Build And Deploy

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      - name: Build application
        run: npm run build
        working-directory: frontend/
        
      - name: Archive build artifacts
        run: |
          mkdir -p tmp/build
          tar -czf tmp/build/build.tar.gz -C backend/build .
          
      - name: Store build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: tmp/build/build.tar.gz
          
  deploy:
    needs: build
    runs-on: ubuntu-22.04

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt
      
      - name: Copy artifacts from previous job
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: tmp/build
              
      - name: Copy build artifacts to Azure VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.AZURE_SSH_USERNAME }}
          SSH_HOSTNAME: ${{ secrets.AZURE_VM_IP }}
          SSH_TARGET_DIR: ${{ secrets.ARTIFACT_TARGET }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > deploy_key
          chmod 600 deploy_key
          eval "$(ssh-agent -s)"
          ssh-add deploy_key

          scp -o StrictHostKeyChecking=no -r tmp/build/build.tar.gz "$SSH_USERNAME"@"$SSH_HOSTNAME":/home/"$SSH_USERNAME"/
          ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOSTNAME" 'mkdir -p '"$SSH_TARGET_DIR"
          ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOSTNAME" 'tar -xzf /home/'"$SSH_USERNAME"'/build.tar.gz -C '"$SSH_TARGET_DIR"' --strip-components=1'
          ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOSTNAME" 'rm /home/'"$SSH_USERNAME"'/build.tar.gz'


      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_SSH_USERNAME }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd shubhrad-01
            git pull
            source env/bin/activate
            cd backend
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --no-input
            deactivate
            
            

