name: Deploy to Azure VM

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JavaScript dependencies
        run: npm ci
        working-directory: frontend/
        

      - name: Deploy to Azure VM
        run: |
          ssh -i "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" shubhrad1@"${{ secrets.AZURE_VM_IP }}" 'cd /path/to/your/django/project && git pull'
          ssh -i "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" shubhrad1@"${{ secrets.AZURE_VM_IP }}" 'cd /path/to/your/django/project && pip install -r path/to/requirements.txt'
          ssh -i "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" shubhrad1@"${{ secrets.AZURE_VM_IP }}" 'cd /path/to/your/django/project && python manage.py migrate'
          ssh -i "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" shubhrad1@"${{ secrets.AZURE_VM_IP }}" 'cd /path/to/your/django/project && python manage.py collectstatic --noinput'
          

