name: Deploy to Azure VM

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JavaScript dependencies
        run: npm ci
        working-directory: frontend/
        

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        env:
          VM_IP: ${{ secrets.AZURE_VM_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
       
        with:
          host: "$AZURE_VM_IP"
          username: shubhrad1
          key: "$SSH_PRIVATE_KEY"
          script: |
            cd shubhrad-01
            git pull
            

